import { build } from "esbuild";

await build({
  entryPoints: ["src/oncall/cli.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  outfile: "bin/pi-kydo.js",
  banner: {
    js: "#!/usr/bin/env node\n// Generated by npm run build:oncall. Edit src/oncall/, not this file.",
  },
});
